apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true

  - name: ClickHouse
    type: grafana-clickhouse-datasource
    access: proxy
    url: http://clickhouse:8123
    database: nextgen_analytics
    basicAuth: false
    editable: true
    jsonData:
      defaultDatabase: nextgen_analytics
      username: default
      timeout: 30
    secureJsonData:
      password: ""