apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - 0-namespace.yml
  - 6-networkpolicies.yml
  - 7-cronjobs.yml
  - admin-stack.yml
  - api-stack.yml
  - blue-green-deployment.yml
  - enterprise-autoscaling.yml
  - hpa-autoscaling.yml
  - istio-authorization-policies.yml
  - meilisearch.yml
  - migration-job.yml
  - ml-service-stack.yml
  - redis-cluster.yml
  - vendor-portal-stack.yml
  - web-stack.yml
  - worker-stack.yml
