apiVersion: v1
kind: Service
metadata:
  name: nextgen-api-svc
  labels:
    app: nextgen-api
spec:
  type: ClusterIP
  selector:
    app: nextgen-api
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
